// <auto-generated />
namespace NeshHouse.Stats.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AuditColumns_HubContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditColumns_HubContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201503310414580_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
